### ISSUE TITLE
When comparing 2 files, the left file is read only.

### ISSUE THREAD

**Issue by softlion** [madskristensen/FileDiffer#19]
And its title is "File Name - copy.cs"

Any way to get left file editable ?

**Comment by njsokalski** [comment]
I have the exact same problem/comment/request. My most common use of this extension (I previously used an external utility not integrated with Visual Studio) is to compare the debug and release versions of my apps, and the one that appears on the right (the one that is editable) is the one that I do not want to change. I would like to see a feature that allows you to choose which file is editable (although I would expect it to be the one in the open solution by default, since that is the code you are supposedly editing).

**Comment by madskristensen** [comment]
Unfortunately, that is not up to this extension since it uses whatever diffing tool ships with VS
