### ISSUE TITLE
Open diff view to paste text from clipboard

### ISSUE THREAD

**Issue by galich** [madskristensen/FileDiffer#7]
Comparing files are great, but how about comparing selected regions from two files? Or pasted text?

**Comment by madskristensen** [comment]
Like compare file or selection with clipboard?

**Comment by galich** [comment]
exactly, user selects a bit of text and copy to clipboard, then select another bit of text (in the same or other file) and diff to clipboard content.

**Comment by fbmnds** [comment]
There is no IntelliSense on [`_dte.Commands.Raise`](https://github.com/madskristensen/FileDiffer/blob/master/src/Commands/DiffFilesCommand.cs#L68). Any idea how to check on an overloaded method operating on strings instead of files? A workaround would be to generate temp files for the clipboards snippets.

I would like to have a modification that would allow to [pick both files](https://github.com/madskristensen/FileDiffer/blob/master/src/Commands/DiffFilesCommand.cs#L79). This would allow to compare any files from disk, not only files within the solution (real use case for me right now). @madskristensen: would you consider a PR?

**Comment by madskristensen** [comment]
This has been added to the latest version of the extension. See the updated readme file for screenshots on how the new features work
